### ISSUE TITLE
v0.6.3 Package broken because python3-django==3.19 is no longer available as a debian package

### ISSUE THREAD

**Issue by jdoubleu** [ArchiveBox/debian-archivebox#19]
After a recent system update, I noticed that `archivebox` doesn't work anymore.

Running `archivebox` always fails with the following error:
```
ValueError: Primary key 'django.db.models.UUIDField' referred by core.apps.CoreConfig.default_auto_field must subclass AutoField.
```

Similar issues raised in the main repo (https://github.com/ArchiveBox/ArchiveBox/issues/738#issuecomment-832072545, https://github.com/ArchiveBox/ArchiveBox/issues/728#issuecomment-831503017) mention that the Django version should be **exactly** `3.19`. However, the debian packaged Django version for _bookworm_ is already at `3.2.19` (see https://packages.debian.org/bookworm/python3-django).

**Comment by pirate** [comment]
Unfortunately the 3.19 -> 3.2 upgrade requires significant work, which may stall the fix here.  I can vendor django as a temporary workaround, but for now I recommend pip installing archivebox after apt installing it, the pip version should take precedent.

**Comment by pirate** [comment]
The 0.7.1 .deb package now just runs `pip install archivebox` in the postinstall script. This means `apt install ./archivebox-0.7.1.deb` works again, but it unfortunately no longer follows Debian's official packaging guidelines to never download things from the internet during build/install time.

I recently switched ArchiveBox from `setup.py` to using PDM for Python package management, but I could find no existing tooling that can automatically create a `.deb`/`apt` package from PDM / `pyproject.toml`, and I don't have the bandwidth to create a tool myself right now. (we were previously using [stdeb](https://github.com/astraw/stdeb))

Eventually I hope to go back to packaging for Debian properly, if anyone has on any suggestions here, I'm open to hearing them!
